version: "3"

services:
  app:
    build: .
    command: sh -c "yarn migration:build && yarn start"
    env_file:
      - .env
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
