version: "3"

services:
  db:
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    image: postgres:12-alpine
    ports:
      - 5432:5432
  app:
    build: .
    stdin_open: true
    tty: true
    command: sh -c "yarn migration:build && yarn start:dev"
    env_file:
      - .env
    expose:
      - ${PORT}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - .:/usr/app
