version: "3"

services:
  db:
    image: postgres:10.6-alpine
    ports:
      - 5432:5432
    volumes:
      - .:/var/lib/postgresql/data
  app:
    build: .
    environment:
      NODE_PATH: .
      NODE_ENV: ${NODE_ENV}
      DB_HOST: ${DB_HOST}
    command: sh -c "yarn migration:build && yarn start"
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - .:/usr/app
