version: "3"

services:
  db:
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    image: postgres:12-alpine
    ports:
      - 5432:5432
  app:
    build: .
    command: sh -c "yarn migration:build && yarn start:dev"
    env_file:
      - .env
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - .:/usr/app
